### ISSUE TITLE
Implement the initial query

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#103]
Initial query is the one we run when Arronax launches.

When Arronax launches it should land in **Blocks** entity, pull the details about the **last 100 blocks** and display **Level**, **Timestamp**, **Block Hash**, **Predecessor Hash** of them sort them in descending (highest level to lowest) order

**Comment by Sm00g15** [comment]
handled the initial sorting in #109

**Comment by Sm00g15** [comment]
those values don't appear in order in the attributes array though so when you open the selected columns tab it won't just be the first 4 checked boxes

**Comment by umurb** [comment]
Merged with #109
