### ISSUE TITLE
Add routing for individual operations, accounts, and blocks

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#106]
The user could be interested in searching for a single block. Or when we integrate Arronax to Tezori, we will want to have arronaxurl/[operationID] to take our users to individual pages.

In its first iteration, Arronax should prepare the filters to show the details of this individual entity.

E.g.

Assume I am searching the details for the following operation  `onxTYTrZqx2onvEG4qaBFcSmSXFF6GuZraagYrUnc6uptvSXBwk`

I should be routed through `https://arronax/onxTYTrZqx2onvEG4qaBFcSmSXFF6GuZraagYrUnc6uptvSXBwk`

and I should land on Arronax in `Operations` view with the below preset filter

![screen shot 2019-02-12 at 6 55 05 pm](https://user-images.githubusercontent.com/37525692/52676367-ebd64a00-2ef7-11e9-9687-6c40d5af90a0.png)

and below 6 columns selected:

Kind, Source, Destination, Amount, Fee, Delegate

**Comment by anonymoussprocket** [comment]
implemented as id-based search
