### ISSUE TITLE
Design for queries with no result

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#113]
![no-result-returned](https://user-images.githubusercontent.com/37525692/54282674-e0b41f80-4572-11e9-8167-24ca33eb06ff.png)

We need to display an image / a message when the user query returns null

**Comment by polinasoshkina** [comment]
@umurb Here is the link to the design:
https://share.goabstract.com/f2bb61d6-e574-4822-91cb-c77ce04e4609

**Comment by umurb** [comment]
Fantastic! Thank you, Polina.

Clear Filters: Should return the user back to a clean (reset) filter panel, and show the results of the initial query.
Try Again: Should return the user back to the filter panel with their selected filters

**Comment by umurb** [comment]
Merged with #164
