### ISSUE TITLE
Fix the Filter Number indicator

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#116]
![Screen Shot 2019-03-20 at 4 35 31 PM](https://user-images.githubusercontent.com/37525692/54717275-328a1600-4b2e-11e9-83c8-cfe1e041dd24.png)

Let's update the number indicator with the actual number of filters selected by the user. Should update after every time the user hits `Run`

If there are no filters selected, show no number.

![Screen Shot 2019-03-20 at 4 36 41 PM](https://user-images.githubusercontent.com/37525692/54717352-5e0d0080-4b2e-11e9-9895-48c42c21c0ac.png)

**Comment by Sm00g15** [comment]
This was handled in #138

**Comment by umurb** [comment]
Merged with #138
