### ISSUE TITLE
Run initial queries and load results on the background

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#117]
~~As soon as the user launches Arronax, we should run all necessary queries on the background and cache the results.~~ A user should not have to wait every time they switch the entity

Edit after our discussion with Sean:

Run the initial query for Blocks & keep the user waiting as short as possible. As soon as the results are loaded, run the initial query for Operations and Accounts on the background, and prepare the results for the entity switch.

**Comment by Sm00g15** [comment]
in this case it'd make the first initial load time much longer but then the flow through the site would be faster. A middle ground between the 2 would be to fetch all the initial queries for each tab so the tab switching is fast when they start, but not fetch the values until they click on a select with a low cardinality. Thoughts?

**Comment by umurb** [comment]
Merged with #120
