### ISSUE TITLE
Disable `Add Filter` button until previous filter is complete

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#126]
Currently, a user is allowed to add empty filters back to back. We should disable the `Add Filter` button until the previous filter is completed.

As per styling, cursor: default & 50% opacity should do the trick

**Comment by Sm00g15** [comment]
This code is ready to go, just waiting for the merge of #138 so I can create a PR with only these changes, b/c the code on this ticket relies on those changes.

**Comment by umurb** [comment]
Merged with #140
