### ISSUE TITLE
Run a new query every time a user tries to sort data from a column

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#130]
Recently, we got rid of the **Sort By** selector. Instead of this selector, we should run a new query every time a user clicks on the column name to sort it, and `addOrdering` to our query with the column user selected.

Related to this, remove all references to specific column names: `block_level` and `level`. This should be handled with the combination of new metadata and the above.

**Comment by anonymoussprocket** [comment]
Resolved in #191
