### ISSUE TITLE
Move Columns selector out of the filter box

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#131]
Pending Design

**Comment by polinasoshkina** [comment]
@umurb I wanted to clarify requirements:
1. Remove sort, limit, and columns from the filter panel.
2. Move columns selection outside of filter panel.
3. Set default sort behind the scenes and allow sorting on the individual column level. Are we ok with not allowing sort by columns not displayed?
4. Set default unchangeable limit. Do we need to communicate what it is somewhere?
5. Do we still keep 6 column limit?
6. Is the redesign of column interaction part of this story? e.g. making it clear which columns are selected and when you can no longer select.

**Comment by umurb** [comment]
@polinasoshkina 

1. Yes
2. Yes
3. Correct. The default sorting will happen with block height, descending. Then, users will be able to sort using the column headers. I think is OK to start like this and not allow sorting on hidden columns. So far I've never felt the need to do sorting on hidden columns. Let's wait for the initial feedback and then we can decide.
4. We have a default 5000 limit for now. I think it is a good idea to communicate this to the user. We can also use it to emphasize exporting to csv option. e.g.
'Queries on Arronax are limited to 5000 results. **Export to csv** to see the whole results.'
5. I am OK with removing the limit. Honestly, I had some moments where I wanted to select more than 6 columns playing around. But how do you feel about this? You wanted this limit to disable the horizontal scrolling with the table. If you are going to feel comfortable having horizontal scrolling, I'd say remove it

**Comment by umurb** [comment]
Will be included in #134 - Closing
