### ISSUE TITLE
Add an `Export to CSV` button

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#134]
Pending Design

**Comment by polinasoshkina** [comment]
@umurb Not sure if it's sufficient just to add that button. Will export CSV have a limit? Would the user be able to choose which columns to export or is it all by default?

**Comment by umurb** [comment]
@polinasoshkina Export to CSV won't have a limit. In other words, if a query returns more than 5000 results, we will display the first 5000 on display, but Export to CSV will export the whole thing.

`Export to CSV` should export the fields and columns selected by the user. This should work well after we remove the limit of 6 columns.

**Comment by polinasoshkina** [comment]
@umurb here is the abstract link with the following changes:
+ Columns moved out from filters
+ Added "Export CSV" button
+ Added on hover message when result set exceeds 5k
+ Added hover states 

Abstract link:
https://share.goabstract.com/20bdf17e-c94b-4752-9263-4b7f6adb71b9

Icon file:
[arronax.zip](https://github.com/Cryptonomic/Arronax/files/3129597/arronax.zip)

**Comment by umurb** [comment]
Will create new tickets for these tasks. Closing this issue. Thank you @polinasoshkina for the fonts and the UI, looks amazing
