### ISSUE TITLE
Modal entity-view design

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#136]
Clicking on certain fields in the result set table should bring up a form-based view of the entity being requested like an account, a block, or an operation group.

The three views would be modal pop-ups containing some or all properties of the entity in a specific order. This will not be a metadata driven dynamic view.

**Comment by polinasoshkina** [comment]
Here is the link the basic template design:
https://share.goabstract.com/1db948b0-0290-4785-86e6-852cd5f6dd02?

1. Scrolling of the modal should work as twitter feed scrolling (here is an example https://twitter.com/maht0rz/status/1125827013166739463)
2. Clicking on any linked field morphs the modal into a new detail view modal
3. Use "display name" for labels
4. Clicking on the "x" or outside of the modal closes the modal
5. We should be able to specify the order of the fields to be displayed
