### ISSUE TITLE
Starts with, Ends with, Is null not working

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#144]
3 Operators mentioned in the title are not working.

- [ ] Starts with & Ends with
Although `like` is working fine, I am getting an error when I try to run a query using `Starts with` and `Ends with`.

To reproduce: Go to Accounts tab, add a filter for Account ID.
Account ID **like** TZ1 - works
Account ID **starts with** TZ1 - fails
Account ID **ends with** abc - fails

- [ ] Is null
`Is null` filters do not work. They are not even visible in the predicates array.

![Screen Shot 2019-04-01 at 12 20 27 PM](https://user-images.githubusercontent.com/37525692/55343606-73acef00-5479-11e9-91e9-9ddb055c369a.png)

**Comment by Sm00g15** [comment]
began to fix this in this branch: https://github.com/Cryptonomic/Arronax/tree/bug/144-starts-with

**Comment by umurb** [comment]
Merged with #151
