### ISSUE TITLE
Improve filter validation logic

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Arronax#156]
Make `disableAddFilter` in `components/FilterPanel/index.tsx` a function and account for more conditions where a filter is valid, for example:

- after adding a filter on the operations view (destination is not null) add filter button became disabled and I was not able to add more, even after "run"ing. I'm guessing this is due to filter validation

**Comment by Sm00g15** [comment]
Joe's covered this is PR #157
