### ISSUE TITLE
Add sorting to Column selection screen

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#171]
The selected values in the columns panel should be sortable (drag & drop). The sorting of these columns should determine how we are sorting the columns in the results table.

![sorting](https://user-images.githubusercontent.com/37525692/57158661-f810cb80-6db1-11e9-9d41-59c4c83f45ac.gif)

**Comment by maht0rz** [comment]
I'm going to start working on this as discussed with @anonymoussprocket
