### ISSUE TITLE
UX: Create a collapsed navigation

### ISSUE THREAD

**Issue by navi-arneja** [Cryptonomic/Arronax#383]
Display only blocks, accounts and operations until uncollapsed. Keep the same interaction that we have now with right & left arrows if the nav list is longer than screen width.

https://zpl.io/a3oE47l

**Comment by navi-arneja** [comment]
Display only blocks, accounts and operations until uncollapsed. Keep the same interaction that we have now with right & left arrows if the nav list is longer than screen width.

https://zpl.io/a3oE47l

**Comment by anonymoussprocket** [comment]
done as part of #373.
