### ISSUE TITLE
Update the list of filters to match the latest filters supported by Conseil/ConseilJS

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#56]
ConseilJS now supports a couple more operation filters other than ID and source, please include them in Arronax. 

Specifically, arronax should support the following:
- 'limit', which limits the amount of blocks, operations, or accounts
- 'block_id', or the hash of the block the user is requesting (block_hash in block schema for tezos node)
- 'block_level', the level of the block the user is requesting (
- 'block_netid', the 'chain_id' of the block the user is requesting. This is defined in the block schema for the tezos node
- 'block_protocol', the 'protocol' field in the block schema in the tezos node
- 'operation_id', the hash of the operation the user is requesting, 'hash' in the operation schema
- 'operation_source', 'source' in operation schema for tezos node
- 'operation_destination', 'destination' in operation schema for tezos node
- 'operation_participant', 
- 'operation_kind', the type of operation that is being requested, current ones supported are 'origination', 'delegation', 'seed_nonce_revelation', 'transaction', 'activate_account', 'reveal', 'endorsement'
- 'account_id', hash of the account being requested
- 'account_manager', hash of the manager of the account being requested
- 'account_delegate', hash of the delegate of the account being requested

Filter object in conseiljs for reference: https://github.com/Cryptonomic/ConseilJS/blob/674b14b6ab506bb0411e928d6c5e8f023635bb1d/src/tezos/TezosConseilQuery.ts#L40

**Comment by anonymoussprocket** [comment]
resolved in PR72
