### ISSUE TITLE
Implement the dot representation of hashes

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#93]
Hashes are overwhelming, and we need to have a dotted representation for them.

![hash-dot representatin](https://user-images.githubusercontent.com/37525692/52291544-9a9ae900-2940-11e9-8b80-23f1680884f4.png)

As seen in the above image, every hash should be represented as [First 6 Characters][...][Last 6 Charactes]

As an addition to the dot representation, addresses (hashes starting with tz1, tz2, tz3, and KT1) should have a visual representation of their first and last six characters. To do so, add two ovals, first one representing the first 6 digits of the hash and second one representing the last 6 digits of the hash.

Details for the color coding of the ovals will be discussed soon

**Comment by Sm00g15** [comment]
should the hashes be links to their specific data on TZscan?

**Comment by umurb** [comment]
Merged with #97
