### ISSUE TITLE
Add a Favicon

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#98]
We need a favicon for the site.

**Comment by polinasoshkina** [comment]
@umurb here a favicon package and the source file. It should look something like this: http://elastic-archimedes-cbe9e7.netlify.com/

[arronax-blue-favicon.zip](https://github.com/Cryptonomic/Arronax/files/3046138/arronax-blue-favicon.zip)

[arronax-blue-src.svg.zip](https://github.com/Cryptonomic/Arronax/files/3046141/arronax-blue-src.svg.zip)

**Comment by umurb** [comment]
Thanks, @polinasoshkina. Assigned @Sm00g15 to the ticket

**Comment by umurb** [comment]
Merged with #148
